### ISSUE TITLE
모자이크 기능

### ISSUE THREAD

**Issue by choiyooung** [CAU-OSS-2019/team-project-team11#8]
현재 미리 DB에 사진 있는 사람은 얼굴 보여주고 이 외에 사람들은 모자이크 하는데 , 반대로 특정 사람만 모자이크 하길 원할 수도 있을 것같습니다. 그렇게 되면 현 시스템에서는 그 사람을 제외한 모든 사람의 얼굴의 사진이 들어가야되는 것 같습니다. 따라서 반대되는 기능을 넣으면 다른 용도로도 사용이 가능 할것 같습니다.

**Comment by ddamddi** [comment]
그 기능이 추가된다면 다른용도(ex. 실시간 인터뷰 등)에서 사용하기 좋을 것 같네요.
의견 감사합니다.
